// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7CzhlYA3q4O27p-n3xV5jIhCAZF5Kuo',
    appId: '1:378490127532:web:3c65b0980f36a99ac70b09',
    messagingSenderId: '378490127532',
    projectId: 'dalel-34a9a',
    authDomain: 'dalel-34a9a.firebaseapp.com',
    storageBucket: 'dalel-34a9a.appspot.com',
    measurementId: 'G-ZYW058DM0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMd0oElCfmZm9mQnR9CLDUFc7QJIHHlU8',
    appId: '1:378490127532:android:bb419480d0dc5bc3c70b09',
    messagingSenderId: '378490127532',
    projectId: 'dalel-34a9a',
    storageBucket: 'dalel-34a9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaO_XZF4YoQl61KV5n97XSF-gHHU5cdkQ',
    appId: '1:378490127532:ios:9c7e5c59028bd469c70b09',
    messagingSenderId: '378490127532',
    projectId: 'dalel-34a9a',
    storageBucket: 'dalel-34a9a.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaO_XZF4YoQl61KV5n97XSF-gHHU5cdkQ',
    appId: '1:378490127532:ios:873a147b59788321c70b09',
    messagingSenderId: '378490127532',
    projectId: 'dalel-34a9a',
    storageBucket: 'dalel-34a9a.appspot.com',
    iosBundleId: 'com.example.dalelApp.RunnerTests',
  );
}
